Create New page
Code-Society-Lab/cursif-web pull request #39
Opened 2023-12-23 06:16 UTC by chrisdedman

Added a button to create a new page on the sidebar.

2024-01-09 04:28 UTC, PenguinBoi12 requested changes
![image](https://github.com/Code-Society-Lab/cursif-web/assets/49426163/50458800-2580-4256-99b2-fe17eabddc36)
This should show the "pointer" cursor. 

In general it seem good but there's still weird behaviour about the page list.
![pages](https://github.com/Code-Society-Lab/cursif-web/assets/49426163/6e96ca72-76f4-4ada-b158-233c0587a2f1)

2024-01-09 04:28 UTC, PenguinBoi12 commented on src/app/(protected)/notebooks/[notebook_id]/[page_id]/page.tsx
> +      ownerId
We don't need to query `ownerId` and `ownerType`


Part of the beauty of using GraphQL. We can query only the data we need.

2024-01-09 04:28 UTC, PenguinBoi12 commented on src/app/(protected)/notebooks/[notebook_id]/page.tsx
> +      ownerId
We don't need to query `ownerId` and `ownerType`

2024-02-03 02:39 UTC, chrisdedman commented
I fixed the issues based on your comments. However, I still had some trouble with the rendering of the array after clicking on the + button to create a new page. So, I used the ``location.reload();`` for now. I'm not sure why my array isn't rendered at the same time as I created the new page.

2024-02-27 05:02 UTC, chrisdedman commented
> I fixed the issues based on your comments. However, I still had some trouble with the rendering of the array after clicking on the + button to create a new page. So, I used the `location.reload();` for now. I'm not sure why my array isn't rendered at the same time as I created the new page.

Fixed

2024-03-15 17:20 UTC, PenguinBoi12 approved these changes
This looks good! I think it's ready to be merged.

2024-03-15 17:22 UTC, merged